### ISSUE TITLE
Drawing compound objects not backwards compatible between 2.6.5 and 2.6.4?

### ISSUE THREAD

**Issue by StuartLittlefair** [ejeschke/ginga#561] opened 2017-10-09 14:44 UTC
I have some code which works in 2.6.4 which is raising an error in 2.6.5.

I have a ```CompoundObject``` called ```obj```, which is created from a list, ```l``` of ```Polygons``` and ```Paths``` as so:

```
obj = CompoundObject(*l)
```

I am attempting to display this object inside a ```tkw.ImageViewTk.ImageViewCanvas``` called ```fi``` using:

```
canvas = fi.canvas
canvas.deleteObjectByTag('ccd_overlay')
canvas.add(obj, tag='ccd_overlay', redraw=False)
canvas.update_canvas()
```

which now (2.6.5) produces the following exception:

```
2017-10-09 14:40:23,971 | E | ImageView.py:1264 (redraw_now) | Error redrawing image: float() argument must be a string or a number, not 'generator'
2017-10-09 14:40:23,973 | E | ImageView.py:1269 (redraw_now) | Traceback:
  File "/Users/sl/anaconda3/lib/python3.6/site-packages/ginga/ImageView.py", line 1250, in redraw_now
    self.redraw_data(whence=whence)
  File "/Users/sl/anaconda3/lib/python3.6/site-packages/ginga/ImageView.py", line 1295, in redraw_data
    self.private_canvas.draw(self)
  File "/Users/sl/anaconda3/lib/python3.6/site-packages/ginga/canvas/DrawingMixin.py", line 723, in draw
    super(DrawingMixin, self).draw(viewer)
  File "/Users/sl/anaconda3/lib/python3.6/site-packages/ginga/canvas/CompoundMixin.py", line 141, in draw
    obj.draw(viewer)
  File "/Users/sl/anaconda3/lib/python3.6/site-packages/ginga/canvas/CompoundMixin.py", line 141, in draw
    obj.draw(viewer)
  File "/Users/sl/anaconda3/lib/python3.6/site-packages/ginga/canvas/types/basic.py", line 262, in draw
    cpoints = self.get_cpoints(viewer)
  File "/Users/sl/anaconda3/lib/python3.6/site-packages/ginga/canvas/CanvasObject.py", line 490, in get_cpoints
    return crdmap.data_to(points)
  File "/Users/sl/anaconda3/lib/python3.6/site-packages/ginga/canvas/coordmap.py", line 70, in data_to
    return viewer.tform['data_to_native'].to_(data_arr)
  File "/Users/sl/anaconda3/lib/python3.6/site-packages/ginga/canvas/transform.py", line 68, in to_
    return self.tform2.to_(self.tform1.to_(pts, **kwargs))
  File "/Users/sl/anaconda3/lib/python3.6/site-packages/ginga/canvas/transform.py", line 68, in to_
    return self.tform2.to_(self.tform1.to_(pts, **kwargs))
  File "/Users/sl/anaconda3/lib/python3.6/site-packages/ginga/canvas/transform.py", line 68, in to_
    return self.tform2.to_(self.tform1.to_(pts, **kwargs))
  File "/Users/sl/anaconda3/lib/python3.6/site-packages/ginga/canvas/transform.py", line 397, in to_
    data_pts = np.asarray(data_pts, dtype=np.float)
  File "/Users/sl/anaconda3/lib/python3.6/site-packages/numpy/core/numeric.py", line 531, in asarray
    return array(a, dtype, copy=False, order=order)
```

Any advice as to what's changed would be appreciated!

**Comment by pllim** [comment] 2017-10-09 14:48
What exactly were these objects; i.e., what are in `l`? Were they drawn in WCS space? There were some changes to how WCS coords were passed, but without more info, I can't recall.

**Comment by StuartLittlefair** [comment] 2017-10-09 14:55
Thanks for the quick response - I wasn't sure what kind of info to include in the issue.

The objects are mostly classes inherited from ```Polygon``` defined in pixel-space (the class is included below). There are also two ```Path```s. Defined as 

```
        points = (image.radectopix(ra, dec) for (ra, dec) in (
            (chip_ctr_ra, ybot), (chip_ctr_ra, ytop)
        ))
        hline = Path(points, color='red', linestyle='dash', linewidth=2)
```

I'm guessing it's the definition of ```points``` above as a generator that's causing problems?

Here's the class I derive from ```Polygon``` in case it's not...
```
class CCDWin(Polygon):
    def __init__(self, ra_ll_deg, dec_ll_deg, xs, ys,
                 image, **params):
        """
        Shape for drawing ccd window

        Parameters
        ----------
        ra_ll_deg : float
            lower left coordinate in ra (deg)
        dec_ll_deg : float
            lower left y coord in dec (deg)
        xs : float
            x size in degrees
        ys : float
            y size in degrees
        image : `~ginga.AstroImage`
            image to plot Window on
        """
        points_wcs = (
            (ra_ll_deg, dec_ll_deg),
            wcs.add_offset_radec(ra_ll_deg, dec_ll_deg, xs, 0.0),
            wcs.add_offset_radec(ra_ll_deg, dec_ll_deg, xs, ys),
            wcs.add_offset_radec(ra_ll_deg, dec_ll_deg, 0.0, ys)
        )
        self.points = [image.radectopix(ra, dec) for (ra, dec) in points_wcs]
        super(CCDWin, self).__init__(self.points, **params)
        self.name = params.pop('name', 'window')
```

**Comment by StuartLittlefair** [comment] 2017-10-09 14:58
@pllim yes - its the definition of ```points``` above. Changing to:

```
        points = [image.radectopix(ra, dec) for (ra, dec) in (
            (chip_ctr_ra, ybot), (chip_ctr_ra, ytop)
        )]
        hline = Path(points, color='red', linestyle='dash', linewidth=2)
```

works in both. I'll leave it to you guys to decide if this is a bug or a feature ;)

**Comment by pllim** [comment] 2017-10-09 15:18
Just for the record, which WCS system are you using?

**Comment by StuartLittlefair** [comment] 2017-10-09 15:29
The simple built-in one ```from ginga.util import catalog, dp, wcs```

**Comment by pllim** [comment] 2017-10-09 15:35
What do you see when you do this?
```
>>> from ginga.util import wcsmod
>>> wcsmod.WCS
```

**Comment by StuartLittlefair** [comment] 2017-10-09 16:12
```
wcs_astropy.AstropyWCS
```

**Comment by pllim** [comment] 2017-10-09 18:20
Thank you for all the information. I'll let @ejeschke confirm whether it is a bug or feature in case it is related to #516.

**Comment by ejeschke** [comment] 2017-10-09 19:19
@StuartLittlefair, @pllim, glad you could zero in on the issue so quickly.  Indeed, the representation of points changed in that point release.  It sounds like we just need a coercion in one or more constructors to force the generator to an array (or list).

BTW, great to hear that someone is using the Tk back end!  Legacy interface project?

**Comment by StuartLittlefair** [comment] 2017-10-09 19:35
Yes - a finding chart tool for an instrument whose GUI is in tkinter. 

This way I can reuse the modules from the instrument gui for window setup and S/N calcs.

**Comment by ejeschke** [comment] 2017-10-10 01:26
So it boils down to this:
```
points = (image.radectopix(ra, dec) for (ra, dec) in ((300.0, 22.69), (300.1, 22.69)))
data_pts = np.asarray(points, dtype=np.float)
```
blows up with the exception.  We can correct it like so:
```
points = (image.radectopix(ra, dec) for (ra, dec) in ((300.0, 22.69), (300.1, 22.69)))
data_pts = np.asarray(list(points), dtype=np.float)
```
but I'm not sure that is the most efficient way to do that.  Sort of surprised, really, that `np.asarray` can't handle a generator sequence.

**Comment by ejeschke** [comment] 2017-10-10 01:32
Useful answer (here)[https://stackoverflow.com/questions/367565/how-do-i-build-a-numpy-array-from-a-generator] which basically says that numpy can't know how many elements a generator will make, so it is considered a feature and not a bug insofar as numpy is concerned.  Which maybe should be the case for us as well...

**Comment by ejeschke** [comment] 2017-10-10 01:36
I suppose we could do something like
```if not hasattr(points, '__len__'):
        points = list(points)
```
this handles the case for other things that may not be directly convertible to arrays without a length.

**Comment by ejeschke** [comment] 2017-10-10 03:34
> I suppose we could do something like ...

The more I dig into this, trying to convert the generator iterables at the right spots, the more I realize why probably `numpy` just decided to pass on this.  I think for now we will simply say that points passed to graphics objects need to be finite non-generator sequences.

Relabeling as not a bug and closing.

**Closed by ejeschke** 2017-10-10 03:34 UTC
Labels: question, wontfix
