### ISSUE TITLE
Windows multi-monitor display issue

### ISSUE THREAD

**Issue by robertoabraham** [ejeschke/ginga#789] opened 2019-08-09 21:00 UTC
Hi, I'm running Ginga (the reference viewer) using Windows and it works and looks great on my laptop's display (which has a high DPI screen) when I don't have another monitor hooked up to the computer. However, when I hook my laptop up to a big 27" monitor (which isn't a high DPI display) I can't seem to get a reasonable display on either the laptop's display or the external display, because the fonts are way too big in both cases. Here is what the display on my laptop looks like:

![Capture](https://user-images.githubusercontent.com/1026243/62808300-b5077800-bac5-11e9-96e7-e81c3aa305ac.PNG)

I think this must be happening because Qt (which I presume is doing the rendering of the windows) is having a tough time figuring out what to do with Windows' display scaling needed to cope with my laptop's screen. (I'm currently running at 250% scaling on my laptop screen and 100% scaling on the big monitor which is set up to be my main display). Is this hypothesis likely to be correct, and if so, is there anything I can do about it? I confess that I like Ginga so much I could be persuaded to upgrade to a 4K high DPI display on my main monitor just to handle this issue, but I kind of like my old monitor and would rather not upgrade if I don't have to. In any case, before I buy a new monitor I want to make sure it will fix the issue.

Thank you!

Bob

P.S. I installed Ginga using `conda install ginga -c conda-forge`

**Comment by ejeschke** [comment] 2019-08-10 01:47
Hi Bob, what version of Windows are you running?  I read [here](https://doc.qt.io/qt-5/highdpi.html) some information about Qt HiDPI support on Windows.  It looks like Windows (or Qt) is confused about what the DPI is and maybe not reporting it correctly to the Qt app when you have the second display hooked up.  There is some interesting information about environment variables you can set to override the behavior.  What do you get when you try:
```bash
$ QT_AUTO_SCREEN_SCALE_FACTOR=1 ginga ...
```

**Comment by ejeschke** [comment] 2019-08-10 02:37
Also, try it with value 0; e.g.:
```bash
$ QT_AUTO_SCREEN_SCALE_FACTOR=0 ginga ...
```
Let us know what you discover!

**Comment by robertoabraham** [comment] 2019-08-10 03:51
Hi Eric,

Good news... the problem was fixed by using the 'turn it off and on again' approach. I signed out of the account and then logged back in, and that did the trick. Ginga now looks great on both monitors (the only time it looks bad is when part of the main window is on one monitor and the other part is on the other, and I can certainly live with that). So I guess the lesson is that I just need to log out and log in again when I plug the second monitor into the laptop

By the way, to answer your earlier question, I'm using Windows 10 (version 1903).

The environment variable settings don't seem to make a big difference to the outcome though if the `QT_AUTO_SCREEN_SCALE_FACTOR` variable is set to 0 I do get an error on startup. Setting it to 1 silences the startup error, though in both cases the main window looked OK to me (though I didn't compare them in minute detail with screenshots etc to see what difference it made). Anyway, here's what the console reports in both cases:

```
(base) C:\Users\abrah>SET QT_AUTO_SCREEN_SCALE_FACTOR=0

(base) C:\Users\abrah>ginga
QWindowsWindow::setGeometry: Unable to set geometry 2948x1729+2716+162 on QWidgetWindow/'TopLevelClassWindow'. Resulting geometry:  2932x1680+2724+203 (frame: 16, 72, 16, 16, custom margin: 0, 0, 0, 0, minimum size: 391x26, maximum size: 16777215x16777215).

(base) C:\Users\abrah>SET QT_AUTO_SCREEN_SCALE_FACTOR=1

(base) C:\Users\abrah>ginga

(base) C:\Users\abrah>
```

Anyway, as far as I'm concerned this behaviour is fine and I think I'm good to go. Thanks for your help!

Bob

P.S. Hmm. The bad news is I now don't have an excuse to buy a new 4K display. D'oh!

**Comment by ejeschke** [comment] 2019-08-10 04:14
Good to hear.  I'm running Ginga on a 4Kx4K display and it seems to scale just fine under the version of Linux I'm running without doing anything special with environment variables and what not. I'm hopeful that most modern OSes along with Qt can take care of this so that we don't have to do too many special hacks in the app!

BTW: I'm sure you can justify that 4K display based on some other justification! :smile:

**Comment by ejeschke** [comment] 2019-08-10 04:14
Feel free to close this if you think the problem is solved.

**Closed** 2019-08-10 04:24 UTC
