### ISSUE TITLE
ginga incompatible with latest version of PyQt5 (5.12.3)

### ISSUE THREAD

**Issue by kheegan** [ejeschke/ginga#776] opened 2019-07-04 09:35 UTC
I installed ginga from pip but kept getting the following error message when trying to launch it:

>kg-mbp-2018:bin kheegan$ ginga &
>
>kg-mbp-2018:bin kheegan$ objc[2089]: Class RunLoopModeTracker is implemented in both /Users/kheegan/anaconda/lib/python3.6/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore (0xb1d55a130) and /Users/kheegan/anaconda/lib/libQt5Core.5.dylib (0xb24adca80). One of the two will be used. Which one is undefined.
Traceback (most recent call last):
  File "/Users/kheegan/anaconda/bin/ginga", line 10, in <module>
    sys.exit(_main())
  File "/Users/kheegan/anaconda/lib/python3.6/site-packages/ginga/rv/main.py", line 720, in _main
    reference_viewer(sys.argv)
  File "/Users/kheegan/anaconda/lib/python3.6/site-packages/ginga/rv/main.py", line 715, in reference_viewer
    viewer.main(options, args)
  File "/Users/kheegan/anaconda/lib/python3.6/site-packages/ginga/rv/main.py", line 355, in main
    ginga_toolkit.choose()
  File "/Users/kheegan/anaconda/lib/python3.6/site-packages/ginga/toolkit.py", line 75, in choose
    from ginga.qtw import QtHelp  # noqa
  File "/Users/kheegan/anaconda/lib/python3.6/site-packages/ginga/qtw/QtHelp.py", line 41, in <module>
    from qtpy.QtWebEngineWidgets import QWebEngineView as QWebView  # noqa
  File "/Users/kheegan/anaconda/lib/python3.6/site-packages/qtpy/QtWebEngineWidgets.py", line 22, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ValueError: PyCapsule_GetPointer called with incorrect name'
----
Following some Googling similar error messages, I downgraded PyQt5 from 5.12.3 to 5.10.1 using pip, and after that ginga managed to launch.

**Comment by ejeschke** [comment] 2019-07-05 19:11
@kheegan, thanks for the report. 

It looks like the problem is coming from the `WBrowser` plugin.  Could you confirm by starting ginga with `--disable-plugins=WBrowser` and see if it starts correctly?

 Did you install Qt environment via conda?

**Comment by ejeschke** [comment] 2019-07-05 19:14
> It looks like the problem is coming from the WBrowser plugin. Could you confirm by starting ginga with --disable-plugins=WBrowser and see if it starts correctly?

Sorry, looking again at the traceback it is happening much earlier, in the `import`.

**Comment by ejeschke** [comment] 2019-07-05 19:56
Looks like an error in the [qtpy](https://github.com/spyder-ide/qtpy) package.  I am trying to reproduce it.  We may need to [file a bug](https://github.com/spyder-ide/qtpy/issues).

**Comment by ejeschke** [comment] 2019-07-05 20:09
```bash
$ conda list pyqt
# packages in environment at /home/eric/miniconda3/envs/newqt:
#
# Name                    Version                   Build  Channel
pyqt5                     5.12.3                   pypi_0    pypi
pyqt5-sip                 4.19.18                  pypi_0    pypi
```
```bash
$ conda list ginga
# packages in environment at /home/eric/miniconda3/envs/newqt:
#
# Name                    Version                   Build  Channel
ginga                     2.7.2                    pypi_0    pypi
```
```bash
$ conda list qtpy
# packages in environment at /home/eric/miniconda3/envs/newqt:
#
# Name                    Version                   Build  Channel
qtpy                      1.8.0                    pypi_0    pypi
```
Hmmm...when I install PyQt5==5.12.3 from `pip` and also `ginga` (from pip).  It works for me.  

Might be an issue with mixing Qt from conda with qtpy from pip?

@kheegan, can you try installing via pip?  Make your initial conda environment, but then install qt by `pip install PyQt5==5.12.3` and `pip install ginga`.

**Comment by ejeschke** [comment] 2019-07-05 20:31
Alternatively, you could see if you have an older version of `qtpy` installed and remove that and install a newer version from pip.

Basically, I don't see an issue if you have compatible versions of `pyqt` and `qtpy` installed.

**Comment by ejeschke** [comment] 2019-07-10 21:51
Closing as a non-issue.  We can reopen and/or file an issue with `qtpy` if it looks like there is still an issue.

**Closed by ejeschke** 2019-07-10 21:51 UTC
