### ISSUE TITLE
Cuts Plugin Improvements

### ISSUE THREAD

**Issue by ejeschke** [ejeschke/ginga#131] opened 2015-07-02 04:21 UTC
@pllim writes in issue #120:

* When a cut is Drawn, is it possible to set the left drop-down menu back to "None"? Currently, the menu remains on the latest cut, which defaults to the behavior of overwriting the cut when I draw another line. If I forget to re-select "None" before drawing again, I lose my latest cut. Does that make sense?
* Delete buttons can be disabled when there is nothing to delete. Right now, they just do nothing when you press them anyway, so this is more of a cosmetic improvement.
* Plot should clear completely when the last cut is deleted, or when "Delete All" is pressed. Right now, the last cut is displayed if they are deleted one by one, or the whole plot remains if they are all deleted at once. The remaining plot is not meaningful because it is no longer associated with any cut lines. Again, a cosmetic improvement.
* I notice that the cut color changes when I delete another cut. Personally, I am fine with it, but I don't know if other users will find it confusing. For example, Cut1 is green, Cut2 is red; Then, I delete Cut1, and now Cut2 is green.

**Comment by ejeschke** [comment] 2015-07-02 04:22
Moving cuts improvements over into this new issue to keep from further hijacking the topic in issue #120

**Comment by ejeschke** [comment] 2015-07-02 04:29
@pllim, regarding resetting the menu back to None.  This is a workflow issue.  I suppose it depends on whether you typically make multiple cuts or keep working with a single cut.  Ginga's cuts was modeled after the one in skycat, which just offered a single cut and let you move it around or redraw it.  This is the way most of our personnel use it.  But I think it would be easy to make a preference for this, so that you could choose to have it reset to "None" (or it could say "New Cut").  I think I would choose to make the default as the current operation, however.

@Cadair, do you have an opinion on this?

I think the other suggestions are good.  Regarding the color, it simply cycles through colors so that new cuts are drawn with new colors.  Not sure that this should be so confusing, especially as the cuts are labeled.

**Comment by Cadair** [comment] 2015-07-02 11:02
ping @nabobalis @rupak0577

**Comment by pllim** [comment] 2015-07-02 17:47
@ejeschke , adding "None" or "New Cut" to preferences sounds like a good plan. I'm fine if you want to keep "New Cut" default. As for the colors, I guess the current behavior is fine too if it is too troublesome to modify; It just caught me off-guard the first time I used it, that's all.

**Comment by Cadair** [comment] 2015-07-02 17:50
@pllim I agree with you that None and the colours are both something that could confuse people.

**Comment by rupak0577** [comment] 2015-07-04 04:13
I think 'None' should be changed to 'New Cut' to avoid confusion. I did make the changes for clearing the plot a few days back but haven't committed them yet. The colors issue seems fine, although probably the colors should not change.

**Comment by rupak0577** [comment] 2015-07-04 17:19
Points 2,3 fixed in #124

**Comment by ejeschke** [comment] 2015-07-05 04:04
Great, thanks @rupak0577.  Looks like we could merge that PR unless you are adding more to it.

**Comment by ejeschke** [comment] 2015-07-08 05:31
Dear All,
Could you try commit 52f5313375ebd19fef863e9a7e341d1a9695324d?  This addresses points 1 and 4, I believe.  @rupak0577, if you are not adding more to the PR you can rebase it against this version and we can merge it to address points 2,3.

**Comment by pllim** [comment] 2015-07-08 14:28
@ejeschke , for Point 4, the line colors seem fine now, as in they don't change when I delete one. *But* it would be nice to have the label color to be same as the line color. After I draw several lines close to each other, I can't keep track which label is for which line, because the labels are all light blue.

**Comment by pllim** [comment] 2015-07-08 14:35
Or better(?) still, instead of putting labels on the image (which can cover interesting pixels), perhaps the labels can go into a separate frame in the `Cuts` dialog? For instance, a frame titled `Legend` with a layout as follows:
```
------ Legend ------
(blue line) cuts0   (red line) cuts1
(green line) cuts2
```
Shouldn't be too hard to implement if you visualize them as a plot without grids or labels. And then just replot it when cuts are added/deleted. This is just an idea though.

**Comment by ejeschke** [comment] 2015-07-09 04:01
@pllim, in commit cbcd6b88f58a8327d8dfb3cde4a50df68b184974 I've changed the labels to be the same color as the lines.  The line labels can also be turned off via a preference, and I've added an example preferences file for Cuts in `.../examples/configs/plugin_Cuts.cfg`

I would be open to adding a separate legend/key for the cuts labels.  The logical place would be in the matplotlib figure itself, but I'm concerned that it could become crowded.  Perhaps a separate section as you suggest might work better.  I would welcome a PR to explore either one...

**Comment by ejeschke** [comment] 2015-07-09 04:03
Also, I think the default color set is not ideal.  Some of the colors work well, but others are a bit washed out.  Anyone have a better set of ~16 colors to recommend?

**Comment by ejeschke** [comment] 2015-07-17 22:05
Dear All,
I've merged PR #124.  `Cuts` should now cover all of the points raised above by @pllim.

I'm open to changing the default for `label_cuts` to False, if anyone has an opinion on it.

**Comment by pllim** [comment] 2015-07-20 14:13
@ejeschke et al., thanks for all the improvements. I am currently occupied by a different project, so I'll check them out when I get the chance  in the near future. But I have been following the discussions, and I don't see any issues.

**Comment by rupak0577** [comment] 2015-07-28 15:54
@ejeschke @pllim In commit 3c62712, I have added a legend button for cuts which opens a dialog window showing the cuts with their colors. I would like to know if it can be improved in any way.

**Comment by ejeschke** [comment] 2015-07-29 02:12
@rupak0577 , is that added to this PR that was already merged?

**Comment by pllim** [comment] 2015-07-29 19:06
@rupak0577 , I do not see the "legend" button. I am using the latest dev version of Ginga.

**Comment by pllim** [comment] 2015-07-29 19:35
I think once this missing "legend" button mystery is ratified, we can close this issue.

**Comment by ejeschke** [comment] 2015-07-29 19:39
@rupak0577, can you simply make a new PR with this change?  I think that would be best.  Previous PR was merged.

**Comment by ejeschke** [comment] 2015-07-29 19:40
Oh and for the record, I changed the default set of colors.  Of course this is controlled by a preference and so the user can change these as desired.

**Comment by rupak0577** [comment] 2015-07-29 20:04
@ejeschke @pllim I haven't made a PR yet. It looks like this -
![wi](https://cloud.githubusercontent.com/assets/10296115/8968414/a332b85e-365a-11e5-988a-c035c434acd8.png)

The only thing troubling me is that the code is Qt based and adding that to Cuts seems wrong. And probably it can be made even better.

**Comment by ejeschke** [comment] 2015-07-29 20:06
@rupak0577 , we definitely don't want a Qt only solution.  How about simply adding a key to the matplotlib widget?  It could simply have the labels "cuts0", cuts1", etc. drawn in the proper colors.

**Comment by rupak0577** [comment] 2015-07-29 20:15
@ejeschke You mean the plot? I am not sure how...

**Comment by nabobalis** [comment] 2015-07-29 20:26
you can add legends in matplotlib, you have to label the plot with the label keyword, label = 'name' and call plt.legend(). 

Assuming I've followed the conversation.

**Comment by ejeschke** [comment] 2015-07-30 00:12
@nabobalis, that's what I have in mind.  @rupak0577, if you look at the `Pick` plugin plot you can see this kind of little key in the upper right hand corner of one of the plots.

**Comment by pllim** [comment] 2015-07-30 14:48
@rupak0577 , regarding your screenshot, just naming the colors won't be enough. I need that color actually displayed.

Why? Because I have the ongoing debate with my spouse on whether the school bus is actually yellow or orange. Same school bus. Every morning.

**Comment by Cadair** [comment] 2015-07-30 14:55
XD

**Comment by rupak0577** [comment] 2015-07-30 15:03
@pllim LOL. I was going to make the text colored but it's probably better to use the mpl solution.

**Comment by pllim** [comment] 2015-07-30 16:32
I just found something else (using the latest dev version). Draw a cut in `Cuts` plugin (I used straight line). Close the plugin without deleting the cut line. Re-open the plugin. Now the plot appears smaller (as attached).
![screenshot](https://cloud.githubusercontent.com/assets/2090236/8988935/fe59231a-36b6-11e5-91fc-d394ff09c682.png)

**Comment by rupak0577** [comment] 2015-07-30 17:03
Confirmed with GTK. Does not happen with Qt. 

Another small issue is the buttons get disabled even with a cut present.

**Comment by pllim** [comment] 2015-07-30 17:08
@rupak0577 , I am using Qt that comes with Anaconda:
```
pyqt                      4.11.3                   py27_1  
qt                        4.8.6                         3  
```

**Comment by pllim** [comment] 2015-12-10 17:07
@ejeschke , @rupak0577 

I still see the plot being increasingly small when I have multiple cuts, as shown below.

![screenshot](https://cloud.githubusercontent.com/assets/2090236/11722415/942fdbee-9f36-11e5-93fd-f261e6c1b48f.png)

**Comment by pllim** [comment] 2015-12-10 19:06
I think I addressed the remaining issues for `Cuts` with PR #248. Please review.

**Closed** 2015-12-10 21:22 UTC
Labels: enhancement, reference viewer
